### ISSUE TITLE
Proposal to Update README with Github Actions Workflow Information

### ISSUE THREAD

**Issue by onedesert** [Elph/sync-branch#191]
Hello,

I've been experiencing issues with Github Actions workflows not being triggered. After some research, I found out that this behavior is actually a deliberate decision made by Github. More context can be found [here](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow).

I think that adding a note about this to the README could be beneficial to prevent confusion for future users. Would you be open to a PR where I add this information?

Looking forward to your response.

**Comment by Elph** [comment]
Sound great, any PR is welcome!

**Comment by onedesert** [comment]
@Elph PR summited.
